### ISSUE TITLE
Crash during hand-eye calibration

### ISSUE THREAD

**Issue by Victorlouisdg** [airo-ugent/airo-mono#101]
**Trace**
```
2023-12-20 10:17:21.928 | INFO     | airo_camera_toolkit.calibration.hand_eye_calibration:do_camera_robot_calibration:108 - Saving calibration results to /home/victor/cloth-competition/calibration_2023-12-20_10:15:05/results_n=6
2023-12-20 10:17:22.242 | INFO     | airo_camera_toolkit.calibration.compute_calibration:compute_calibration_all_methods:281 - Board poses were detected in 6 of the calibration samples.
2023-12-20 10:17:22.257 | INFO     | airo_camera_toolkit.calibration.compute_calibration:compute_calibration_all_methods:288 - Residual error Tsai: 0.0312
2023-12-20 10:17:22.287 | INFO     | airo_camera_toolkit.calibration.compute_calibration:compute_calibration_all_methods:288 - Residual error Park: 0.0314
Traceback (most recent call last):
  File "/home/victor/anaconda3/envs/cloth-competition/bin/airo-camera-toolkit", line 33, in <module>
    sys.exit(load_entry_point('airo-camera-toolkit', 'console_scripts', 'airo-camera-toolkit')())
  File "/home/victor/anaconda3/envs/cloth-competition/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/anaconda3/envs/cloth-competition/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/anaconda3/envs/cloth-competition/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/victor/anaconda3/envs/cloth-competition/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/anaconda3/envs/cloth-competition/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/airo-mono/airo-camera-toolkit/airo_camera_toolkit/cli.py", line 51, in calibrate_with_ur
    do_camera_robot_calibration(mode, aruco_dict, charuco_board, camera, robot, calibration_dir)
  File "/home/victor/airo-mono/airo-camera-toolkit/airo_camera_toolkit/calibration/hand_eye_calibration.py", line 109, in do_camera_robot_calibration
    poses_dict, errors_dict = compute_calibration_all_methods(
  File "/home/victor/airo-mono/airo-camera-toolkit/airo_camera_toolkit/calibration/compute_calibration.py", line 307, in compute_calibration_all_methods
    draw_base_pose_on_image(image, intrinsics, camera_pose, mode, tcp_poses_in_base[-1])
  File "/home/victor/airo-mono/airo-camera-toolkit/airo_camera_toolkit/calibration/compute_calibration.py", line 237, in draw_base_pose_on_image
    draw_frame_on_image(image, base_pose_in_camera, intrinsics)
  File "/home/victor/airo-mono/airo-camera-toolkit/airo_camera_toolkit/calibration/fiducial_markers.py", line 186, in draw_frame_on_image
    charuco_se3 = SE3Container.from_homogeneous_matrix(frame_pose_in_camera)
  File "/home/victor/airo-mono/airo-spatial-algebra/airo_spatial_algebra/se3.py", line 58, in from_homogeneous_matrix
    return cls(SE3(matrix))
  File "/home/victor/anaconda3/envs/cloth-competition/lib/python3.10/site-packages/spatialmath/pose3d.py", line 981, in __init__
    raise ValueError("bad argument to constructor")
ValueError: bad argument to constructor
```

**Comment by Victorlouisdg** [comment]
Data from that calibration run: https://ugentbe-my.sharepoint.com/:u:/g/personal/victorlouis_degusseme_ugent_be/EWrQPKTK8VpPsZGoHxJv4b0BhJVZouCJjY9kJBAu1M-ypg?e=aHd6Lp

Seems like the crash happened when visualizing the result from Park.
