### ISSUE TITLE
Realsense camera cannot be instantiated more than once

### ISSUE THREAD

**Issue by tlpss** [airo-ugent/airo-mono#109]
**Describe the bug**
cannot run a script that opens a realsense camera more than once.

**To Reproduce**

run the manual tests twice. first time works. second time gives error:
```
(airo-mono) (base) tlips@olifant:~/Code/contact_graspnet$ python robot/airo-mono/airo-camera-toolkit/airo_camera_toolkit/cameras/realsense/realsense.py 
the rectified intrinsics matrix = 
 [[1372.6    0.   956.7]
 [   0.  1369.6  557. ]
 [   0.     0.     1. ]]
Camera matrix should be as expected:
     cx,cy are +- 1/2 of the image resolution
     and fx,fy should match the camera documentation.
     All values are in pixels.
     Press a key if all seems reasonable.
Traceback (most recent call last):
  File "/home/tlips/Code/contact_graspnet/robot/airo-mono/airo-camera-toolkit/airo_camera_toolkit/cameras/realsense/realsense.py", line 148, in <module>
    test.manual_test_rgb_camera(camera)
  File "/home/tlips/Code/contact_graspnet/robot/airo-mono/airo-camera-toolkit/airo_camera_toolkit/cameras/manual_test_hw.py", line 25, in manual_test_rgb_camera
    image = camera.get_rgb_image()
  File "/home/tlips/Code/contact_graspnet/robot/airo-mono/airo-camera-toolkit/airo_camera_toolkit/interfaces.py", line 63, in get_rgb_image
    self._grab_images()
  File "/home/tlips/Code/contact_graspnet/robot/airo-mono/airo-camera-toolkit/airo_camera_toolkit/cameras/realsense/realsense.py", line 107, in _grab_images
    self._composite_frame = self.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
```

unplugging the camera fixes the issue.

**Expected behavior**

**Screenshots**

**Environment:**

- Python:

**Additional context**

**Comment by m-decoster** [comment]
[This fix](https://github.com/IntelRealSense/librealsense/issues/6628#issuecomment-646558144) seems to work for me. Needs more testing.

Basically, add

```
ctx = rs.context()
devices = ctx.query_devices()
for dev in devices:
    dev.hardware_reset()
```

on line 62 of realsense.py
